### ISSUE TITLE
Does it work for Angular 5+ ?

### ISSUE THREAD

**Issue by dtomaszewski** [ui-router/sample-app-angular-hybrid#27]
Hi,

Why sample app was downgraded to Angular 4? Does angular-hybrid UIRouter AoT compilation and lazy loading work for Angular 5 and AngularCompilerPlugin instead of AotPlugin ?

**Comment by christopherthielen** [comment]
It's updated for Angular 5 now.

There's one issue that I've run across.  It seems that you have to explicitly inject tokens, not use Typescript typing metadata.

For example, see [this commit to the sample app](https://github.com/ui-router/sample-app-angular-hybrid/commit/53f438e2828e11c0730508e989d7d04f154f9bd8).  The tokens from `@uirouter/core` are explicitly injected like so: 
```
@Inject(StateProvider) $state: StateProvider
```

**Comment by christopherthielen** [comment]
To follow up on my previous comment about `@Inject()`, the problem was that the app was running in JIT mode because of a misconfigured AngularCompilerPlugin.

To fix the problem in JIT mode, I [added `reflect-metadata` to index.html](https://github.com/ui-router/sample-app-angular-hybrid/commit/05ee1cd78fda8810cfd1c6a5c0692da98218da67).

However, I later [fixed AoT compile](https://github.com/ui-router/sample-app-angular-hybrid/commit/ce067b56b6c945c3158d615a7a9c640cfd847876) also.
